/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
package com.jasperreporttest.filetransfer.controller;

import com.jasperreporttest.filetransfer.FileTransfer;
import java.lang.String;
import java.io.IOException;
import com.wavemaker.runtime.file.model.DownloadResponse;
import org.springframework.web.multipart.MultipartFile;
import java.io.File;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

@RestController
@RequestMapping(value = "/fileTransfer")
public class FileTransferController {

    @Autowired
    private FileTransfer fileTransfer;

    @RequestMapping(value = "/doDownload", produces = "application/octet-stream", method = RequestMethod.GET)
    public DownloadResponse doDownload(@RequestParam(value = "filename", required = false) String filename) throws IOException {
        return fileTransfer.doDownload(filename);
    }

    @RequestMapping(value = "/doUpload", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "")
    public void doUpload(@RequestPart(value = "file") MultipartFile file) throws IOException {
        fileTransfer.doUpload(file);
    }

    @RequestMapping(value = "/uploadDir", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "")
    public File getUploadDir() {
        return fileTransfer.getUploadDir();
    }
}
