/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
package com.jasperreporttest.filetransfer.controller;

import com.jasperreporttest.filetransfer.FileTransfer;
import org.springframework.web.multipart.MultipartFile;
import java.io.IOException;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

@RestController
@RequestMapping(value = "/fileTransfer")
public class FileTransferController {

    @Autowired
    private FileTransfer fileTransfer;

    @RequestMapping(value = "/doUpload", method = RequestMethod.POST)
    public void doUpload(@RequestPart(value = "file") MultipartFile file) throws IOException {
        fileTransfer.doUpload(file);
    }
}
